services:
  bc-dockge:
    restart: unless-stopped
    image: louislam/dockge:latest
    ports:
      - 5001:5001
    volumes:
      - ~/busyvolumes/bd-dockge:/app/data
    environment:
      - DOCKGE_STACKS_DIR=/opt/busystacks/
      - DOCKGE_ENABLE_CONSOLE=true
networks: {}
