services:
  busydockge-service:
    image: louislam/dockge:latest
    container_name: busydockge-container
    restart: unless-stopped
    volumes:
      - ~/busyvolumes/busydockge-data:/app/data
    ports:
      - 5001:5001
    environment:
      - DOCKGE_STACKS_DIR=/opt/busystacks/
      - DOCKGE_ENABLE_CONSOLE=true
networks:
    busynetwork:
        name: bridge
        external: true
