services:
  busykdmongo-service:
    image: mongo
    container_name: busykdmongo-container
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    ports:
      - 27017:27017
    volumes:
      - /home/busyvolumes/busykdmongo-db:/data/db
      - /home/busyvolumes/busykdmongo-dbconfig:/data/configdb
    networks:
      - busynetwork-containers
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}
    labels:
      komodo.skip: null # Prevent Komodo from stopping with StopAllContainers
  busykdcore-service:
    image: ghcr.io/moghtech/komodo-core:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: busykdcore-container
    restart: unless-stopped
    depends_on:
      - busykdmongo-service
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    ports:
      - 9120:9120
    networks:
      - busynetwork-containers
    env_file: ./.env
    environment:
      KOMODO_DATABASE_ADDRESS: busykdmongo-service:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
    volumes:
      ## Core cache for repos for latest commit hash / contents
      - /home/busyvolumes/busykdcore-repocache:/repo-cache
    labels:
      komodo.skip: null
        # Prevent Komodo from stopping with StopAllContainers
        # The Komodo Periphery service
  busykdpr-service:
    image: ghcr.io/moghtech/komodo-periphery:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: busykdpr-container
    restart: unless-stopped
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    networks:
      - busynetwork-containers
    env_file: ./.env
    environment:
      PERIPHERY_REPO_DIR: ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/repos
      PERIPHERY_STACK_DIR: ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/stacks
      PERIPHERY_SSL_KEY_FILE: ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/ssl/key.pem
      PERIPHERY_SSL_CERT_FILE: ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}/ssl/cert.pem
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      ## Specify the Periphery agent root directory - must be the same inside and outside the container.
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
      ## Custom location for docker compose repo
      - /home/busyvolumes/busykdpr-compose:/mnt/user/compose
    labels:
      komodo.skip: null # Prevent Komodo from stopping with StopAllContainers
networks:
  busynetwork-containers:
    external: true

