services:
  busyuk-service:
    container_name: busyuk-container
    restart: unless-stopped
    image: louislam/uptime-kuma:latest
    ports:
      - 3001:3001
    volumes:
      - ~/busyvolumes/busyuk-data:/app/data
    environment:
      - UMASK=0022
      - DOCKGE_ENABLE_CONSOLE=true
      - TZ=Europe/Amsterdam
    networks:
      - busynetwork-containers
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:3001
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
networks:
  busynetwork-containers:
    external: true
